os: osx
language: objective-c
osx_image: xcode9
xcode_project: Waypoint.xcodeproj
xcode_scheme: WaypointTravisCI
podfile: Podfile

notifications:
   email:
      on_success: never
      on_failure: always

before_install:
   - brew update
   - brew outdated xctool || brew upgrade xctool

script:
   - xcodebuild clean build test -workspace Waypoint.xcworkspace -scheme WaypointTravisCI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0'

