os: osx
language: objective-c
osx_image: xcode9
xcode_project: Waypoint.xcworkspace
xcode_scheme: WaypointTravisCI

notifications:
   email:
      on_success: never
      on_failure: always

before_install:
   - brew update
   - brew outdated xctool || brew upgrade xctool

script:
   - xcodebuild clean build test -project Waypoint.xcworkspace -scheme WaypointTravisCI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0'

