language: objective-c
osx_image: xcode9
xcode_project: Waypoint.xcodeproj
xcode_scheme: WaypointTravisCI

notifications:
   email:
      on_success: never
      on_failure: always

before_install:
   - brew update
   - brew install xctool

